// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationApi.Infrastructure;

#nullable disable

namespace ReservationApi.Infrastructure.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    partial class ReservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReservationApi.Infrastructure.Entities.ResourceDbEntity", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResourceId");

                    b.ToTable("Resources", (string)null);
                });

            modelBuilder.Entity("ReservationApi.Infrastructure.ReservationDbEntity", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReservingPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasFilter("[ResourceId] IS NOT NULL");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("ReservationApi.Infrastructure.ReservationDbEntity", b =>
                {
                    b.HasOne("ReservationApi.Infrastructure.Entities.ResourceDbEntity", "Resource")
                        .WithOne("Reservation")
                        .HasForeignKey("ReservationApi.Infrastructure.ReservationDbEntity", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ReservationApi.Infrastructure.Entities.ResourceDbEntity", b =>
                {
                    b.Navigation("Reservation");
                });
#pragma warning restore 612, 618
        }
    }
}
